scripts:
  - name: Get Flutter Dependencies
    script: |
      flutter clean
      flutter pub get
  - name: Set iOS Deployment Target to 13.0
    script: |
      sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/' ios/Podfile || echo 'platform :ios, "13.0"' >> ios/Podfile
  - name: Install CocoaPods
    script: |
      cd ios
      pod install
      cd ..
  - name: Build Flutter for iOS
    script: |
      flutter build ios --release --no-codesign
  - name: Export IPA
    script: |
      flutter build ipa --export-options-plist=ios/ExportOptions.plist
