workflows:
  ios-release-workflow:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods
    code_signing:
      certificates:
        - certificate_url: ENCRYPTED_CERTIFICATE_URL
          certificate_password: ENCRYPTED_CERTIFICATE_PASSWORD
      provisioning_profiles:
        - PROFILE_NAME.mobileprovision
    scripts:
      - name: Install dependencies and CocoaPods
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS release
        script: flutter build ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
