workflows:
  ios-release-workflow:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods
    scripts:
      - name: Get Flutter Dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build Flutter for iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Export IPA
        script: |
          flutter build ipa --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
