workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Prebuild iOS (no codesign)
        script: flutter build ios --release --no-codesign
      - name: Pod install
        script: |
          cd ios
          pod install
      - name: Archive
        script: |
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            archive
    artifacts:
      - build/ios/ipa/*.ipa
