scripts:
  - name: Get dependencies
    script: flutter pub get

  - name: Install CocoaPods
    script: |
      cd ios
      pod install

  - name: Archive iOS project
    script: |
      xcodebuild -workspace ios/Runner.xcworkspace \
        -scheme Runner \
        -configuration Release \
        -archivePath build/Runner.xcarchive \
        -destination 'generic/platform=iOS' \
        archive
