workflows:
  ios-release-workflow:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods
    scripts:
      - name: Clean & Get Flutter packages
        script: |
          flutter clean
          flutter pub get

      - name: Build iOS to generate Podfile
        script: |
          flutter build ios --release --no-codesign || true

      - name: Enforce iOS 13 in Podfile
        script: |
          echo ">>> Patching Podfile for iOS 13"
          sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/' ios/Podfile \
            || echo 'platform :ios, "13.0"' >> ios/Podfile
          cat ios/Podfile

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Export IPA
        script: |
          flutter build ipa --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
