# Uncomment this line to define a global platform for your project
platform :ios, '13.0'  # <-- Set minimum iOS version to 13.0 or higher

# CocoaPods analytics sends network stats; disable if you want
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}


def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  raise 'Generated.xcconfig must exist. Run "flutter pub get" first.' unless File.exist?(generated_xcode_build_settings_path)

  File.readlines(generated_xcode_build_settings_path).each do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise 'FLUTTER_ROOT not found in Generated.xcconfig'
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  use_frameworks!  # or `use_modular_headers!` depending on your setup

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Add any other pods you need here, for example:
  # pod 'Firebase/Core'
end
